### ISSUE TITLE
set flags

### ISSUE THREAD

**Issue by Atipriya** [lkorigin/debspawn#17]
Hi @ximion 
I have a question.
How can I set CFLAGS  or CXXFLAGS while building the package?
When I try to use `debspawn build buster --buildflags='-g'` or 
`debspawn build buster --buildflags='-O1'` 
I get error `dpkg-buildpackage: error: unknown option or argument -O1`. Can't I pass -g or -O1 to buildflags?

Thank you!

**Comment by jeremiah** [comment]
Are you passing 'O1' or '01'? That is to say, are you passing the capital letter "O" and the number "1" or are you passing "0" (zero) and "1"?

**Comment by ximion** [comment]
@Atipriya These flags are passed to dpkg itself, they are *not* passed to GCC & Co (simply because we don't know the invocation of those and don't set environment variables so the build is isolated).
What you actually want to do is configure dpkg to apply the right buildflags. See https://man7.org/linux/man-pages/man1/dpkg-buildflags.1.html on information about that. Please note that `-g -O2` is already Debian's default.

If you want to always compile with specific flags in your debspawn container, the easiest way to achieve that would be to log into the container (`debspawn login <suite> --persistent`) and edit `/usr/local/etc/dpkg/buildflags.conf`.
Temporarily changing those flags isn't possible at the moment - that would require passing environment variables like `DEB_BUILD_OPTIONS` through into the container, and we don't do that. You can edit the `debian/rules` file of the respective package to set your desired flags though.

**Comment by Atipriya** [comment]
> Are you passing 'O1' or '01'? That is to say, are you passing the capital letter "O" and the number "1" or are you passing "0" (zero) and "1"?

I was trying with 'O1' not '01'.

@ximion @jeremiah  Thank you!
