### ISSUE TITLE
ERROR: Can not update "amber-amd64": The configuration does not exist.

### ISSUE THREAD

**Issue by jeremiah** [lkorigin/debspawn#3]
I'm unable to update images with debspawn, I get this error;

`ERROR: Can not update "amber-amd64": The configuration does not exist.`

I cannot create images with debspawn either;

`/usr/local/bin/debspawn run --external-command --artifacts-out=/srv/artifacts/1111/ amber /home/jeremiah/code/shell/build-pureos.sh` produces;

ERROR: Can not run command in "amber-amd64": The base image does not exist.

This is true for 0.2.1 and 0.2.2

**Comment by ximion** [comment]
If you run `debspawn update --help` it will tell you that the architecture is a separate argument.
So, to update the `amber` image on a host that already is `amd64`, just run `debspawn update amber`.
If you did actually create an image for a different architecture than that of the host, running  `debspawn update amber -a amd64` will work too.

**Comment by ximion** [comment]
Actually, this command:
```
debspawn run amber -x --artifacts-out=/srv/artifacts/1111/  /home/jeremiah/code/shell/build-pureos.sh
```
Should work. Can you please check if an `amber` image was actually created? (running `debspawn create amber` will tell you, `ls /var/lib/debspawn/containers/` will as well)
Can you check that there aren't any special paths set in `/etc/debspawn/global.json` that may interfere with what you want to do?
If all of this looks good, please reopen this issue, because then there may be a real bug here...

**Comment by jeremiah** [comment]
Amber was never created. :-/ It's being created at the moment.
